### PR TITLE
Add .io file support

### PR DESCRIPTION
**Pull request by The0x539**
Should be self-explanatory.

This is mostly for my own personal convenience, and hopefully that of others.

### CODE REVIEW

**Comment by ScanMountGoat** [comment]
If we only need model.ldr, I would just extract the file contents and store them in the resolver. There probably isn't a need to store the archive itself and deal with RefCell.

**Comment by The0x539** [comment]
I can make that change, but the idea was that this design would make it a bit easier to add custom-part extraction in a later update.

**Comment by ScanMountGoat** [comment]
Are custom parts just ldraw files? I was thinking this could be edited later to just be a `HashMap<String, Vec<u8>>` to represent the relevant archive files. If they aren't ldraw files, the new data can be added to the source map.

**Comment by The0x539** [comment]
Sure, whatever.

**Comment by The0x539** [comment]
Done.

**Comment by ScanMountGoat** [comment]
It seems to be working well from my tests. Thanks.

**Pull request merged**
