### PR TITLE
Improve the node DSL

### PR DESCRIPTION
**Pull request by The0x539**
I have some longer-term machinations that benefit from the DSL being as nice as possible.

The `@` syntax may be slightly strange, but the way I see it, it's a little more concise for something that's used on nearly every node, and it separates the cosmetic `location` from the functional other stuff.

This also contains two quick fixes for bugs I introduced with my previous PR by foolishly neglecting to actually test my changes.

### CODE REVIEW

**Comment by The0x539** [comment]
I don't have any other changes planned for the immediate future after this one, so this would probably be a good time to cut a release.

**Comment by ScanMountGoat** [comment]
The usage of the @ operator makes sense when read aloud in English but doesn't match @ being intended solely for matrix multiplication. I don't think it saves much space compared to using a function parameter.

Is there a reason the group name is set using a decorator and not a function parameter?

**Comment by The0x539** [comment]
> Is there a reason the group name is set using a decorator and not a function parameter?

I don't see the advantage to having it as a function input. That would require specifying it at every usage site, and if two sites used different names for some reason (why?), then you'd have two redundant node groups with identical trees.

> doesn't match @ being intended solely for matrix multiplication

Doesn't `pathlib` overload `/`?

> I don't think it saves much space compared to using a function parameter.

When arguments are split into lines, it saves a line by putting it with the close-paren. In shorter cases, it's often the difference between splitting and not splitting. A positional argument after the (newly positional) `inputs` would share at least *some* of the savings, I guess, but I also see value in having this separate from all the other node configuration.

**Comment by ScanMountGoat** [comment]
> It's often the difference between splitting and not splitting

You could also avoid splitting by just setting the location on a new line. Lines like `rotation @ (-380, -318)` are going to be very confusing to people unfamiliar with the code compared to `rotation.location = (-380, -318)`.

> That would require specifying it at every usage site

Isn't this already handled by calling `_shader_node_group` internally? You could also pass the name as an argument like `graph.group_node("Group", create_group, ...)`. This doesn't statically enforce that the names match up between usages, but groups are often only used once in the code in practice.

**Comment by The0x539** [comment]
> compared to rotation.location = (-380, -318)

Okay, sure. Maybe this was a bit overly fancy.

> You could also pass the name as an argument like `graph.group_node("Group", create_group, ...)`

Why pass it at all? What's the point? What's the use case?

**Comment by ScanMountGoat** [comment]
> Why pass it at all? What's the point? What's the use case?

I'm referring to the code that caches node group creation by name. If `bpy.data.node_groups.get(name)` is none, the function would be called to create the node group. We really only need to prevent initializing the node group in every color's material. The performance impact of accidentally creating "Normals" and "Normal" with identical nodes in the same material will be small. There are probably better ways of doing it that don't require the reader to understand new syntax like `@group`.

**Comment by The0x539** [comment]
Is the objection mostly about the decorator? I thought it was about where the name is specified.

Tree constructors come with a bit of boilerplate. `_shader_node_group` helps with that, but I feel we can do better. Keeping the functions as initializers and moving the get-or-create logic into `NodeGraph.group_node` would accomplish some of that, but would increase the complexity of that method (in addition to the group name thing, it now needs to take an initializer function instead of just a tree).

If this seems like an excessive DRY mentality considering the modest amount of node groups currently in this project, it's because I have plans (and working prototypes!) to mechanically port the material definitions from other import plugins, and more notably from Eyesight, which uses a _lot_ of groups.
I could just use ugly autogenerated straight-bpy Python (for want of an official text format to serialize nodes), but I want to have the converted output be as easy to read and/or maintain than the original representation, if not even easier.

**Comment by ScanMountGoat** [comment]
> would increase the complexity of that method (in addition to the group name thing, it now needs to take an initializer function instead of just a tree).

Is the node tree ever set without a function call? This would just change remove the () from the current code. The approach with `@group` removes the boilerplate for caching node trees, but that could just be moved into `graph.group_node(...)`. I would rather add a parameter than introduce less common language features.

```python
# Proposed changes
main_normals = graph.group_node(normals_node_group())

# Name parameter
main_normals = graph.group_node("Normals", normals_node_group)
```

> mechanically port the material definitions from other import plugins

This would be a nice feature especially for Studio materials. I'm not sure how much needs to be ported exactly. I'd be happy to discuss this more in a separate issue.

**Comment by The0x539** [comment]
> Is the node tree ever set without a function call?

I assumed it would be necessary, but on further thought I can't actually think of a case, present or future, that would require it. Still nice to have, but on further thought I think I can overload it with the help of some `isinstance` checks.

> I would rather add a parameter than introduce less common language features.

After reflecting on it, this seems a bit more acceptable than I originally considered it. However, how would you feel about "automatically" determining the name using either the function name (`.__name__` ->remove the `node_group` affix -> convert to title case) or a docstring (perhaps specifically taking the first line to leave room for prose)?

**Comment by ScanMountGoat** [comment]
>  function name (.__name__ ->remove the node_group affix -> convert to title case)

I'm fine with this approach. Documentation changing the way the code behaves doesn't seem very intuitive to me.

**Comment by The0x539** [comment]
Implemented. Seems to work nicely, and the ergonomics are satisfactory.

**Pull request merged**
